apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc-standard-sc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  # The standard storage class uses Delete ReclaimPolicy
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 1Gi
