apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example-sts-delete-rc
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: example-delete-rc
  serviceName: "example-delete-rc"
  replicas: 1
  template:
    metadata:
      labels:
        app: example-delete-rc
    spec:
      containers:
        - name: busybox
          image: busybox:latest
          command: ["sh", "-c", "sleep infinity"]
          volumeMounts:
            - name: example-pv
              mountPath: /mnt/data
      volumes:
        - name: example-pv
          persistentVolumeClaim:
            claimName: example-pvc-standard-sc
