apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 1Gi
  selector:
    matchLabels:
      type: hostPath
