default_install_hook_types:
  - pre-commit
  - pre-push
default_stages:
  - pre-commit
  - pre-push

repos:
  - repo: local
    hooks:
      - id: kubeconform
        name: kubeconform
        entry: kubeconform -summary
        language: system
        # exclude validating helm charts
        files: ^r1-monitoring/.*\.yaml$

      # validate the rendered Helm chart manifests with kubeconform
      - id: kubeconform-helm-template
        name: kubeconform-helm-template
        entry: bash
        args:
          - -c
          - >-
            helm template validate ./r2-chart/monitoring |
            kubeconform -summary -
        language: system
        files: ^r2-chart/monitoring/
        pass_filenames: false

      - id: markdownlint
        name: markdownlint
        entry: markdownlint-cli2
        # exclude `kubernetes-tasks-r[0-9].md`
        args:
          - "**/*.{md,MD}"
          - "#kubernetes-tasks-r[0-9].md"
        language: system
        pass_filenames: false

      - id: helmlint
        name: helmlint
        entry: helm lint ./r2-chart/monitoring
        language: system
        files: ^r2-chart/
        pass_filenames: false
