apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 1Gi
  selector:
    matchLabels:
      type: hostPath
    # alternatively
    # matchExpressions:
    #   key: type
    #   operator: In
    #   values:
    #     - hostPath
