alertmanager:
  image:
    repository: prom/alertmanager
    tag: "v0.33.1"
  replicaCount: 1
  storageClassName: standard
  pvcSize: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

grafana:
  image:
    repository: grafana/grafana
    tag: "13.0"
  replicaCount: 1
  adminUser: admin
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

kubeStateMetrics:
  image:
    repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
    tag: "v2.19.0"
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

nodeExporter:
  image:
    repository: prom/node-exporter
    tag: "v1.12.1"
  resources:
    requests:
      cpu: 100m
      memory: 50Mi
    limits:
      cpu: 200m
      memory: 100Mi

podinfo:
  image:
    repository: stefanprodan/podinfo
    tag: "6.14.1"
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

prometheus:
  image:
    repository: prom/prometheus
    tag: "v3.13.1"
  replicaCount: 1
  tsdbRetention: 15d
  storageClassName: standard
  pvcSize: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
