apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-node-exporter-service" (include "monitoring.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: monitoring
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  selector:
    app: node-exporter
  ports:
    - name: node-exporter
      protocol: TCP
      port: 9100
      targetPort: 9100
