apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: alertmanager
  name: alertmanager
  namespace: monitoring
spec:
  replicas: {{ .Values.alertmanager.replicaCount }}
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - image: >-
            {{ printf "%s:%s"
              .Values.alertmanager.image.repository
              .Values.alertmanager.image.tag
            }}
          name: alertmanager
          ports:
            # Stick to image default
            # EXPOSE map[9093/tcp:{}]
            - containerPort: 9093
          resources:
            requests:
              cpu: {{ .Values.alertmanager.resources.requests.cpu }}
              memory: {{ .Values.alertmanager.resources.requests.memory }}
            limits:
              cpu: {{ .Values.alertmanager.resources.limits.cpu }}
              memory: {{ .Values.alertmanager.resources.limits.memory }}
          volumeMounts:
            # Stick to image default
            # VOLUME [/alertmanager]
            # CMD ["--storage.path=/alertmanager"]
            - name: alertmanager-storage
              mountPath: /alertmanager
            # Stick to image default
            # CMD ["--config.file=/etc/alertmanager/alertmanager.yml"]
            - name: alertmanager-config-file
              mountPath: "/etc/alertmanager/"
              readOnly: true
      volumes:
        - name: alertmanager-config-file
          secret:
            secretName: alertmanager-secret
  volumeClaimTemplates:
    - metadata:
        name: alertmanager-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.alertmanager.storageClassName | quote }}
        resources:
          requests:
            storage: {{ .Values.alertmanager.pvcSize | quote }}
