apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-podinfo-service" (include "monitoring.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: monitoring
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  selector:
    app: podinfo
  ports:
    - protocol: TCP
      port: 9898
      targetPort: 9898
