apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-grafana-service" (include "monitoring.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: monitoring
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
