apiVersion: v1
data:
  admin-pass: {{ required "grafana.adminPassword is required" .Values.grafana.adminPassword | b64enc | quote }}
kind: Secret
metadata:
  name: {{ printf "%s-grafana-secret" (include "monitoring.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: monitoring
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
