apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-sc
  namespace: monitoring
  labels:
    type: hostPath
spec:
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate
  capacity:
    storage: 1Gi
  storageClassName: "sc-retain"
