apiVersion: v1
data:
  prometheus.yml: |
    # source: https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus.yml
    # my global config
    global:
      scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
      # scrape_timeout is set to the global default (10s).

    # Alertmanager configuration
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              # See https://github.com/grafana/grafana/issues/46434
              # - host.docker.internal:9093 # alertmanager
              - alertmanager:9093

    # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"

    # A scrape configuration containing exactly one endpoint to scrape:
    # Here it's Prometheus itself.
    scrape_configs:
      # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
      # - job_name: "prometheus"
        # metrics_path defaults to '/metrics'
        # scheme defaults to 'http'.
        # static_configs:
          # - targets:
            # Static configs, requires port-forward
            # - localhost:9090
            # # See https://github.com/grafana/grafana/issues/46434
            # - host.docker.internal:8080 # kube-state-metrics - metrics
            # - host.docker.internal:8081 # kube-state-metrics - telemetry
            # - host.docker.internal:9100 # node-exporter
            # - host.docker.internal:9898 # podinfo
            # # The label name is added as a label `label_name=<label_value>` to any timeseries scraped from this config.
            # # labels:
            # #   app: "prometheus"
        # scrape_native_histograms: true
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_endpoints_name]
            regex: 'node-exporter-service'
            action: keep
      - job_name: 'kube-state-metrics'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_endpoints_name]
            regex: 'kube-state-metrics-service'
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            regex: metrics
            action: keep
      - job_name: 'podinfo'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_endpoints_name]
            regex: 'podinfo-service'
            action: keep
kind: ConfigMap
metadata:
  name: prometheus-configmap
  namespace: monitoring
