apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-state-metrics-cr
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - pods
      - services
      - resourcequotas
      - replicationcontrollers
      - limitranges
      - namespaces
      - persistentvolumes
      - persistentvolumeclaims
      - endpoints
      - secrets
    verbs: [list, watch]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - statefulsets
      - replicasets
    verbs: [list, watch]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: [list, watch]
